/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto9_SignUp;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author hcholes
 */
public class Conexion extends javax.swing.JFrame {

   
   
    public Conexion() {
        initComponents();
        pnl_cubrir.setBackground(new Color(0,0,0,200));
         setLocationRelativeTo(null);
         
         
//         ImageIcon imagen =new ImageIcon("/Proyecto9_SignUp/imagenes/user-icon.png");
//         Icon icono=new ImageIcon(imagen.getImage().getScaledInstance(jLabel4.getWidth(),jLabel4.getHeight(),Image.SCALE_DEFAULT));
//         jLabel4.setIcon(icono);
//         this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btn_signup = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        text_nomusuario = new javax.swing.JTextField();
        txt_clave = new javax.swing.JPasswordField();
        pnl_cubrir = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(32, 33, 35));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(57, 113, 177));
        jLabel1.setText("Nombre Usuario");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 120, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 300, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(57, 113, 177));
        jLabel2.setText("Contraseña");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 80, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(57, 113, 177));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 20, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 300, 10));

        btn_signup.setBackground(new java.awt.Color(0, 0, 102));
        btn_signup.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btn_signup.setForeground(new java.awt.Color(255, 255, 255));
        btn_signup.setText("Entrar");
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });
        jPanel2.add(btn_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 300, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto9_SignUp/imagenes/icono1.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        text_nomusuario.setBackground(new java.awt.Color(32, 33, 35));
        text_nomusuario.setForeground(new java.awt.Color(255, 255, 255));
        text_nomusuario.setText("hcholes");
        text_nomusuario.setBorder(null);
        jPanel2.add(text_nomusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 300, 20));

        txt_clave.setBackground(new java.awt.Color(32, 33, 35));
        txt_clave.setForeground(new java.awt.Color(255, 255, 255));
        txt_clave.setText("12345");
        txt_clave.setBorder(null);
        jPanel2.add(txt_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 300, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 509, 450));

        pnl_cubrir.setBackground(new java.awt.Color(0, 0, 0));
        pnl_cubrir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Script MT Bold", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("2018");
        pnl_cubrir.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Papyrus", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 255));
        jLabel9.setText("BIBLIOTECA");
        pnl_cubrir.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("Script MT Bold", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Puerto Berrio - Antioquia");
        pnl_cubrir.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        jLabel11.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("IE Alfonso Lopez Pumarejo");
        pnl_cubrir.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        getContentPane().add(pnl_cubrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 450));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto9_SignUp/imagenes/bf002.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed

   
        try {
				Connection con= null;
				con= getConection() ;
				PreparedStatement ps;
				ResultSet res;
				ps= con.prepareStatement("select * from tb_usuario1");
				res=ps.executeQuery();
				String nombre=text_nomusuario.getText();
				char[] arrayC = txt_clave.getPassword(); 
                                String contr = new String(arrayC); 
                              	while(res.next()) {
                                    
                                            
                                                
					if ((nombre.equals(res.getString("usuario"))) && (contr.equals(res.getString("clave")))){
					idempl=res.getInt("id");
                                     
					this.dispose();
					 Principal p=new Principal();
					    p.setVisible(true);
						break;
					}else {
						JOptionPane.showMessageDialog(null, "No Existe usuario con estos Datos");
					}
					
				}
				con.close();
				}catch(Exception e) {
					JOptionPane.showMessageDialog(null, "No Existe usuario con estos Datos");
					
				}        // TODO add your handling code here:
    }//GEN-LAST:event_btn_signupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conexion().setVisible(true);
            }
        });
    }
    
    	public static final String URL="jdbc:mysql://127.0.0.1/biblioteca";
	public static final String USERNAME="biblioteca";
	public static final String PASSWORD="12345";
        public static int idempl;
	//private JTextField txt_nomusuario;
	//private JTextField txt_clave;
	
	public static Connection getConection() {
		Connection con= null;
		try {
			Class.forName("com.mysql.jdbc.Connection");
			con= (Connection) DriverManager.getConnection(URL,USERNAME,PASSWORD);
			
		}catch(Exception e) {
			JOptionPane.showMessageDialog(null, "No hay Conexion con la base de datos");
		}
		return con;
		
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_signup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel pnl_cubrir;
    private javax.swing.JTextField text_nomusuario;
    private javax.swing.JPasswordField txt_clave;
    // End of variables declaration//GEN-END:variables

}
